# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ implementation of the dlm.lpl
#' 
#' @param Yt_ the vector of observed time series
#' @param Ft_ the matrix of covariates
#' @param delta discount factor
#' @param m0_ the value of the prior mean
#' @param CS0_ controls the scaling of the prior variance
#' @param n0 prior hypermarameter
#' @param d0 prior hypermarameter
#' @export
dlmLplCpp <- function(Yt_, Ft_, delta, m0_, CS0_, n0, d0) {
    .Call(`_multdyn_dlmLplCpp`, Yt_, Ft_, delta, m0_, CS0_, n0, d0)
}

