# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dlmFiltCpp <- function(Yt_, Ft_, delta, m0_, CS0_, n0, d0) {
    .Call('mdmwarwick_dlmFiltCpp', PACKAGE = 'mdmwarwick', Yt_, Ft_, delta, m0_, CS0_, n0, d0)
}

