# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dlmLplCpp <- function(Yt_, Ft_, delta, m0_, CS0_, n0, d0) {
    .Call(`_multdyn_dlmLplCpp`, Yt_, Ft_, delta, m0_, CS0_, n0, d0)
}

